[server]
address = "127.0.0.1"
port = 8080

[database]
url = "AutoShopService"
user = "user"
password = "password"

[cors]
allowed_origins = "*"
allowed_methods = "*"
allowed_headers = "*"

[logging]
level = "Info"
pattern = "%d{yyyy-MM-dd HH:mm:ss} - %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
file = "logs/app.log"
clear_Date = 31
